server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-Credentials: true
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleados/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativos/**
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/autorizaciones/**
        - id: reloj-service
          uri: lb://reloj-service
          predicates:
            - Path=/clock/**
        - id: reloj-service
          uri: lb://reloj-service
          predicates:
            - Path=/schedules/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/** 
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/actuator/**        