server:
  port: 8094
  forward-headers-strategy: framework
spring:
  application:
    name: planilla-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db:3306/planilla
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}